# picom.conf
backend = "glx";
vsync = true;

# Transparency
inactive-opacity = 0.65;
active-opacity = 0.75;
frame-opacity = 1.0;

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Exclude video wallpaper from opacity/shadows
opacity-rule = [
  "100:class_g = 'mpv'",
  "100:name *?= 'xwinwrap'"
];

shadow-exclude = [
  "class_g = 'mpv'",
  "name *?= 'xwinwrap'"
];
